# Generated by Django 2.2.1 on 2019-05-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('card_number', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('mobile', models.TextField()),
                ('number_plate', models.TextField()),
                ('destination', models.TextField()),
                ('purpose', models.TextField()),
                ('intime', models.DateTimeField(auto_now_add=True)),
                ('outtime', models.DateTimeField()),
            ],
        ),
    ]
